# The URL the site will be built for
base_url = "https://harryob.github.io/od-dm-reference"

[markdown]
highlight_code = true
# Includes the DreamMaker syntax highlighting
extra_syntaxes_and_themes = ["syntaxes"]


[extra]
# Used to link to the repository in pages
repo = "https://github.com/harryob/od-dm-reference"
branch = "main"
