# The URL the site will be built for
base_url = "https://ref.opendre.am"

[markdown]
highlight_code = true
# Includes the DreamMaker syntax highlighting
extra_syntaxes_and_themes = ["syntaxes", "themes"]
highlight_theme = "css"
highlight_themes_css = [
    { theme = "visual-studio-dark", filename = "syntax-dark.css" },
    { theme = "visual-studio-light", filename = "syntax-light.css" }
]

[slugify]
paths = "safe"

[extra]
# Used to link to the repository in pages
repo = "https://github.com/OpenDreamProject/od-dm-reference"
branch = "main"
