[package]
name = "od_ref_bot"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/OpenDreamProject/od-dm-reference/"
license = "MIT"

[dependencies]
poise = "0.6.1"
regex = "1.11.1"
tokio = {version = "1.41.1", features = ["rt-multi-thread"]}
toml = "0.8.19"
