name: Update from DMStandard

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: "ref"

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4

      - name: Checkout documentation tool
        uses: actions/checkout@v3
        with:
          repository: "OpenDreamProject/OpenDream"
          ref: "b40e36a2f55e2dc5954f76db6f7ec6f36de63f6e"
          path: "oddt"

      - name: Build documentation tool
        run: |
          cd oddt
          git submodule update --init --recursive
          dotnet build -o ../oddt-bin OpenDreamDocumentationTool
          cd ..

      - name: Get DMStandard
        uses: actions/checkout@v3
        with:
          repository: "OpenDreamProject/OpenDream"
          path: od-master

      - name: Run Documentation Tool
        run: |
          dotnet oddt-bin/OpenDreamDocumentationTool.dll --documentation=ref --standard=od-master/DMCompiler/DMStandard

      - name: Commit
        continue_on_error: true
        run: |
          cd ref
          git config --local user.email "action@github.com"
          git config --local user.name "Autodoc"
          git pull origin main
          git add content
          git commit -m "Automatic DMStandard update" -a || true
          git push -f -u origin autodoc-update

      - name: Create Pull Request
        if: ${{ success() }}
        run: |
          gh pr create --title "Automatic Reference Update" --body "This pull request updates the reference based on the [DMStandard](https://github.com/OpenDreamProject/OpenDream/tree/master/DMCompiler/DMStandard), as generated by the [Documentation Tool](https://github.com/harryob/OpenDream/tree/oddt/OpenDreamDocumentationTool)."
