name: Build and Deploy

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install Zora
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.18.0

      - name: Install Stork
        uses: baptiste0928/cargo-install@v3.1.0
        with:
          crate: stork-search
          version: "1.6.0"

      - name: Build project
        run: npm run build

      - name: Generate Index
        run: |
          stork build --input public/toml/index.html --output public/search.st

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
