name: Deploy PR previews

on:
  pull_request_target:
    branches:
      - main

env:
  DEPLOY_REPO_OWNER: harryob
  DEPLOY_REPO: od-ref-preview

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Configure Base Directory
        run: sed -i 's/base_url = ".*"/base_url = "https:\/\/${{ env.DEPLOY_REPO_OWNER }}.github.io\/${{ env.DEPLOY_REPO }}\/pr-${{ github.event.number }}"/' config.toml

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install Zora
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.18.0

      - name: Install Stork
        uses: baptiste0928/cargo-install@v3.1.0
        with:
          crate: stork-search
          version: "1.6.0"

      - name: Build project
        run: npm run build:index

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./public/
          umbrella-dir: .
          deploy-repository: ${{ env.DEPLOY_REPO_OWNER }}/${{ env.DEPLOY_REPO }}
          token: ${{ secrets.PREVIEW_TOKEN }}
