name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install Zora
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.18.0

      - name: Build project
        run: ZOLA_ENV=dev zola build
